package dalle

import "fmt"

type imageCommandOptionType uint8


// The code block defines an enumeration type called imageCommandOptionType that is used to represent different types of command options for the DALL-E API. 
// The enumeration contains three constants: imageCommandOptionPrompt, imageCommandOptionSize, and imageCommandOptionNumber. 
// These constants are used to represent the prompt, size, and number of images to be generated by the API.
const (
	imageCommandOptionPrompt imageCommandOptionType = 1
	imageCommandOptionSize   imageCommandOptionType = 2
	imageCommandOptionNumber imageCommandOptionType = 3
)




// String returns the string representation of the imageCommandOptionType.
// The String method is defined for the imageCommandOptionType enumeration to return a string representation of the enumeration value. 
// The method uses a switch statement to return the appropriate string representation for each enumeration value.
func (t imageCommandOptionType) String() string {
	switch t {
	case imageCommandOptionPrompt:
		return "prompt"
	case imageCommandOptionSize:
		return "size"
	case imageCommandOptionNumber:
		return "number"
	}
	return fmt.Sprintf("ApplicationCommandOptionType(%d)", t)
}
